name: Release Package

on:
  workflow_dispatch:
    inputs:
      php_version:
        type: string
        required: true
        description: PHP version
        default: "8.3"
      phalcon_version:
        type: string
        required: true
        description: cphalcon version
        default: "5.8.0"
      miko_pbx_version:
        type: string
        required: true
        description: MikoPBX version
        default: "dev-develop"

jobs:
  ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          PHP_VERSION=${{ github.event.inputs.php_version }}
          PHALCON_VERSION=${{ github.event.inputs.phalcon_version }}
          MIKO_PBX_VERSION=${{ github.event.inputs.miko_pbx_version }}
